title: Портфолио Azarov
name: Azarov Portfolio
email: azarov@email.com
description: Мои проекты и кейсы по кибербезопасности, серверам и AI

url: https://buhtig-sudo-azar.github.io
baseurl: /al-folio

blog: false
news: false
selected_papers: false
social: false
latest_posts: false
cv_pdf: false
cv_note: false

projects: true
masonry: false
theme_color: dark

navbar_items:
  - title: Проекты
    url: /projects/

plugins:
  - jekyll-email-protect
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-paginate-v2

third_party_libraries:
  analytics:
    umami:
      enabled: false