source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate'
    gem 'jekyll-sitemap'
    gem 'jekyll-target-blank'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'htmlcompressor'
    gem 'htmlbeautifier'
    gem 'jekyll-strapi'
    gem 'jekyll-relative-links'
end
