name: ðŸ› Report a bug
description: Any errors.
labels: ["needs triage", "bug"]
body:
  - type: markdown
    attributes:
      value: >
        Before you go any further. Is this really a **ðŸ› bug**?

        If it's a question about how al-folio works, have a look at our [documentation](https://github.com/alshedivat/al-folio/blob/master/README.md),
        [frequently asked questions](https://github.com/alshedivat/al-folio/blob/master/FAQ.md),
        [past questions](https://github.com/alshedivat/al-folio/discussions/categories/q-a),
        or [ask a question](https://github.com/alshedivat/al-folio/discussions/new?category=q-a).

  - type: checkboxes
    id: requirements
    attributes:
      label: Have you checked that your issue isn't already filed?
      description: >
        Please check if somebody else has already filed the same issue.
        If you find a similar issue, please add a ðŸ‘ reaction or comment on the original post.
      options:
        - label: I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
          required: true
        - label: Yes, I have checked that this issue isn't already filed.
          required: true

  - type: input
    attributes:
      label: Bug description
      description: A description of the ðŸ› bug.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce the bug
      description: Provide steps to reproduce the ðŸ› bug.
      placeholder: |
        Include steps to reproduce, the expected behaviour, and the actual behaviour.

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error messages and logs
      description: >
        Provide any error messages and/or logs
      placeholder: "Copy the complete error messages and logs"
      value: |
        ```
        The error message you got, with the full traceback if available. Please paste it between these triple backticks.
        ```
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      description: select all OSs where you have experienced this issue
      multiple: true
      options:
        - Linux
        - Mac
        - Windows
        - Not applicable (e.g. you're using GitHub Pages or other hosting)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Where are you seeing the problem on?
      description: select all environments where you have experienced this issue
      multiple: true
      options:
        - "Running locally with Docker (docker compose)"
        - "Running locally with Docker (devcontainer)"
        - "Running locally without Docker"
        - "Deployed site"
    validations:
      required: true

  - type: textarea
    attributes:
      label: More info
      description: Add any other info about the issue here.
      placeholder: |
        Add any other context about the problem here, such as versions of the libraries if running without docker, screenshots, links to the deployed site, etc.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy coding!**"
