FROM mcr.microsoft.com/devcontainers/jekyll:2-bullseye

RUN sudo apt update && sudo apt upgrade -y && \
    sudo apt install libpng-dev libjpeg-dev libtiff-dev -y && \
    sudo apt install imagemagick -y
    

