name: Render a CV

on:
  push:
    branches:
      - main
      - master
    paths:
      - "_data/cv.yml"
  workflow_call: # to make the workflow triggerable from other workflows (release.yaml)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install RenderCV
        run: |
          pip install -r requirements.txt
      - name: RenderCV
        run: |
          cv_file=$(find _data  -maxdepth 1 -type f -name "cv.yml")
          if [ -z "$cv_file" ]; then
            echo "No cv.yml file found!"
            exit 1
          fi
          rendercv render $cv_file --pdf-path "assets/pdf/example_pdf.pdf"
      - name: Upload rendercv_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Push the changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "render the latest CV"
          git push
